FROM go:latest

LABEL app="build-gobingwallpaper"
LABEL REPO="https://github.com/genzj/gobingwallpaper"

ENV GOROOT=/usr/lib/go \
    GOPATH=/gopath \
    GOBIN=/gopath/bin \
    PROJPATH=/gopath/src/github.com/genzj/gobingwallpaper

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

WORKDIR /gopath/src/github.com/genzj/gobingwallpaper

CMD ["make","build-alpine"]
